name: CI - Maven Build with Cucumber Tests and Reporting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      # Step 3: Create configuration file
      - name: Create configuration file
        run: |
          touch configuration.properties
          echo "key=${{ secrets.API_KEY }}" >> configuration.properties
          echo "token=${{ secrets.API_TOKEN }}" >> configuration.properties
          echo "username=${{ secrets.USERNAME }}" >> configuration.properties
          echo "password=${{ secrets.PASSWORD }}" >> configuration.properties

      # Step 4: Run Maven build and Cucumber tests
      - name: Build with Maven and run Cucumber tests
        run: |
          CUCUMBER_PUBLISH_TOKEN=${{ secrets.CUCUMBER_REPORT_TOKEN }} mvn clean verify

      # Step 5: Upload test results to GitHub for visibility
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-report.html
          retention-days: 30
